### ISSUE TITLE
Orthanc ability to trigger

### ISSUE THREAD

**Issue by cquennouelle** [bat3/Health-Barbecue#2]
- [ ] Check if Orthanc is able to trigger an event to the MetaDataDB when a change in the DICOM DB occurs, or if a pulling has to be implemented.

**Comment by MineAlisco** [comment]
Natively, Orthanc don't have the ability to trigger event when DICOM images are uploaded.
But we can implement this behavior according to this example: https://book.orthanc-server.com/plugins/python.html#listening-to-changes
