### ISSUE TITLE
Reverse proxy

### ISSUE THREAD

**Issue by ptitdam2001** [bat3/Health-Barbecue#25]
In order to use Orthanc API and to expect CORS, we should integrate a reverse proxy

We should have 2 reverse proxy.
One for development. (with Webpack for example)
One for deployment (with NGinx for example)

- [x] 1st revproxy : configured to roote to the development .Net Core API. (localhost, but different port)

- [x] 2nd revproxy : configured to route to the prod API (most likely port 80)

**Comment by Nalien** [comment]
We should have 2 reverse proxy.
One for development. (with Webpack for example)
One for deployment (with NGinx for example)

[] 1st revproxy : configured to roote to the development .Net Core API. (localhost, but different port)
[] 2nd revproxy : configured to roote to the prod API (most likely port 80)
