### ISSUE TITLE
Couldn't connect to Docker daemon on macOS

### ISSUE THREAD

**Issue by oderewonko** [bat3/Health-Barbecue#9]
I got the following error while trying to use the command `docker-compose -f "docker-compose.yml" up -d --build` mentioned in the README:
```
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```
I have macOS Catalina (10.15.4) and I installed docker and docker-compose with the command `brew install docker docker-compose`. Maybe some documentation is missing on how Docker should be started because I cannot connect to the addresses localhost:4000 or localhost:8042.

**Comment by ptitdam2001** [comment]
@oderewonko you should use the branch develop (we use git flow)

**Comment by oderewonko** [comment]
> @oderewonko you should use the branch develop (we use git flow)

I will try on the develop branch with another method to install Docker (this time: `brew cask install docker`) which may be more "official."
